### PR TITLE
Adom Lock with Contextmanager

### PR DESCRIPTION
**Pull request by icovada**
This PR adds a couple extras like removing unused imports and a dangerous default "{}" in a function call

Breaking changes:
- login() and logout() return None, not a Session()
- login() raises ValueError if login fails

It looks enormous because of the formatting I've run on it.

### CODE REVIEW

**Comment by icovada** [comment]
Added commits 946394 and e108e3a with ContextManagers.

The goal is to avoid leaving open sessions and/or stale ADM locks should your code have an issue between open and close, you can call this library like so:

```
with FortiManager([data]) as fm:
    with Lock([data]) as admlock:
        fm.do_stuff()
```

instead of 
```
fm = FortiManager()
fm.login()
fm.lock_adm("whatever")
fm.do_stuff()
fm.unlock_adm("whatever")
fm.logout()

**Comment by icovada** [comment]
Done.
Final code should be:

```
with FortiManager([data]) as fm:
    adm_lock = fm.get_lock()  # can pass an ADOM name to get a lock for that ADOM
    with adm_lock:
        do_stuff()
```

**Comment by moustic999** [comment]
Hello, It seems there is a missing "return self" in the __enter__ method of FortiManager. This make the with statement giving None Object !

**Comment by icovada** [comment]
Oops... well this PR is already merged, I'd need a new one, can't you fix this yourself?

**Pull request merged**
